apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  labels:
    app: apache-webapp
    type: front-end
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: webapp
    type: front-end
