apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
    type: db
spec:
  containers:
    - image: meprabhu/docker-images:sql-v2
      name: mysql-container
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password@123"
      ports:
        - containerPort: 3306
